// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace OnDuty.iOS
{
	public partial class AppMainController : UITabBarController
	{
		public AppMainController (IntPtr handle) : base (handle)
		{
		}

       
	}
}
